name: Deploy To Server Using SSH

on:
    push:
        branches:
            - master # Trigger push on main branch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.DEPLOY_PATH }}
                      git checkout main
                      git pull
                      composer install
                      php artisan migrate
                      php artisan optimize
                      php artisan cache:clear
                      php artisan config:clear
                      php artisan route:clear
                      php artisan view:clear
                      php artisan clear-compiled
